name: daily-cron
on:
  schedule:
    - cron: "0 1 * * *"
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call our API rio route
        run: |
          curl 'https://wisevestcapital.com/api/automateInvestmentRio'
